name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Adjust this if you have a different default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can adjust the Node.js version if needed

      - name: Install Firebase Tools
        run: npm install -g firebase-tools  # Install firebase-tools globally

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PACKING_DISPATCH_REWAMP }}"
          projectId: packing-dispatch-rewamp
          channelId: live
          expires: 7d
          entryPoint: .  # Adjust if needed, points to the root of the project
          firebaseToolsVersion: latest
